spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  application:
    name: eureca-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka1


---
spring:
  profiles: test
  application:
    name: eureca-server
server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka1
